### ISSUE TITLE
Нет проверки на правильно введенную почту

### ISSUE THREAD

**Issue by adideas** [DarkCoder30/Full-stack-app#10]
Нет проверки на валидность почты именно со стороны бек 
Последствия не отправится письмо и тд.... (user controller create)

**Comment by DarkCoder30** [comment]
При создании пользователя подразумевается в правилах обязательная проверка всех полей
"email: check('email', 'Некорректный email.').isEmail(),", file: user.rules (проверка делается по regexp'y)
