### ISSUE TITLE
У токена не используется одно очень важное свойство

### ISSUE THREAD

**Issue by adideas** [DarkCoder30/Full-stack-app#4]
У токена не используется одно очень важное свойство "jti"обычно оно используется для контроля выданных токенов. Благодаря ему можно просто и быстро отозвать токен и за него цепляется refresh token. это своего рода уникальный идентификатор токена который нужно хранить в БД. Но не токен.

Именно таким образом настраивается связь между accessToken и refreshToken.

```js
payload: {
   ...
   jti: ?????????
   ...
}
```

Даже когда происходит logout по старому токену можно еще отправлять запросы какое либо время.
Но при этом refreshToken стирается с БД что не даст получать дальнейший доступ к данным.

**Comment by DarkCoder30** [comment]
will used.
