### ISSUE TITLE
Модель пользователя отдается с паролем 

### ISSUE THREAD

**Issue by adideas** [DarkCoder30/Full-stack-app#7]
Это то что модель пользователя отдается фронту с паролем пусть даже хешированым. Просто даже что бы не было соблазна надо его скрыть или при отправки спрятать или заменить на что угодно другое например на пробел.

Например как указано тут
https://mongoosejs.com/docs/tutorials/getters-setters.html

И таким же подходом использовать bcrypt для хеширования пароля (просто это максимально центральная точка)
https://mongoosejs.com/docs/tutorials/getters-setters.html#setters

Или сделать как было бы намного правильнее (https://github.com/DarkCoder30/Full-stack-app/blob/master/server/api/modules/user/user.model.js)
До
```js
  email: {
    type: String,
    required: true,
    unique: true,
    max: 25,
  },
  password: {
    type: String,
    required: true,
    min: 8,
  },
  isActivated: {
    type: Boolean,
    default: false
  },
```

После
```js
  email: {
    type: String,
    required: true,
    unique: true,
    max: 25,
  },
  password: {
    type: String,
    required: true,
    min: 8,
    select: false // Убрать из селекта
  },
  isActivated: {
    type: Boolean,
    default: false
  },
```
С последующими исправлениями. 

Есть еще вариант оборачивать Response (Объект который проверит что у текущей модели есть приватное свойство и будет его скрывать) 

Или вообще прибегнуть к new Symbol("password") что бы при сериализации сразу же убирался и не отправлялся. При этом доступ к этой переменой останется.

**Comment by DarkCoder30** [comment]
Ээм... На фронт ни в каком виде пароль не улетает

**Comment by adideas** [comment]
Не знал сорен не увидел обработку
